### ISSUE TITLE
马铠默认鉴定符配置中的属性与武器鉴定符配置属性相重

### ISSUE THREAD

**Issue by haiman233** [SlimefunGuguProject/Bump#101]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Bump/issues)，且没有找到相同的问题

### 问题描述

马铠默认鉴定符配置中的属性与武器鉴定符配置属性相重，与wiki不符

### 复现步骤

打开配置appraise-types就可以看到

### 预期行为

这wiki和配置今天必须死一个（bushi

### 服务端软件

Purpur

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

 b6fa180-canary

### 插件版本

30

**Comment by ybw0014** [comment]
emm可能搞马铠的时候搞错了？晚点再看看
