### ISSUE TITLE
Appraisal Instrument dupes itself

### ISSUE THREAD

**Issue by IAISI** [SlimefunGuguProject/Bump#169]
### Checklist

- [X] You are using official version downloaded from Guizhan Builds (https://builds.guizhanss.net)
- [X] You did not modify the jar file
- [X] You do not have CS-CoreLib installed
- [X] You searched existing issues, and could not find any existing bug report on this

### Description

Appraisal Instrument from Bump sometimes dupes itself.

### Reproduction Steps

You just break it after placing it fast, place a block instead where it would have been, and it just drops the bell even though you already broke it and its in your inventory

### Expected Behavior

I'm not sure what is dropping extra bells, but I assume it shouldn't happen?

### Server log

There are none.

### Error report

There are none.

### Server Software

Paper

### Minecraft Version

1.18.x

### CS-CoreLib Version

- [X] I don't have CS-CoreLib installed

### Slimefun version

> sf versions
[12:49:21 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-318 (MC: 1.20.2)
Slimefun 4.9-UNOFFICIAL
Metrics-Module #29
Java 17

Installed Addons: (14)
  Gastronomicon vDEV - 8 (git 76336191)
  FastMachines vBuild 12 (git 8276239)
  SoundMuffler v1.0-SNAPSHOT
  Bump vBuild 40 (git 811005e)
  SfChunkInfo vDEV - 8 (git b1b94abb)
  DynaTech vMain - 5
  ExtraGear vDEV - 13 (git c62047e2)
  SlimefunLuckyBlocks vUNOFFICIAL
  ExoticGarden vUNOFFICIAL
  SlimeHUD vDEV - 11 (git b6dc2d53)
  InfinityExpansion vMODIFIED
  LiteXpansion vMODIFIED
  ExtraHeads vDEV - 25 (git 8c29f73a)
  FluffyMachines v1.0.0

Running custom built SlimeFun bbfb9734b9f549d7e82291eff041f9b666a61b63, we only nerfed enchant levels a bit.

### Plugin version

Bump version Build 40 (git 811005e)

**Comment by ybw0014** [comment]
Cant reproduce on my test server. Can you provide a video of the reproduction?

**Comment by IAISI** [comment]
I can't reproduce it right now, we had this reported by one of our players, in between we've updated to 1.20.4 and SF so I'm not quite sure what to do now, I think we can assume it's been fixed and ill get back to you if anyone manages to replicate.
