### ISSUE TITLE
Bump not loading

### ISSUE THREAD

**Issue by gcars06** [SlimefunGuguProject/Bump#25]
### Checklist

- [X] You are using official version downloaded from Guizhan Builds (https://builds.guizhanss.net)
- [X] You did not modify the jar file
- [X] You do not have CS-CoreLib installed
- [X] You searched existing issues, and could not find any existing bug report on this

### Description

When the server is starting, bump gives error that seem to be linked to languages or lore.
(sensibletoolbox filled my log with errors, made it too long for pastebin, had to cut it out)

### Reproduction Steps

1 Download jar
2 Put into plugin folder
3 Change language to english
4 Start server

### Expected Behavior

For bump to be correctly loaded into the server

### Server log

https://pastebin.com/bD8NBswG

### Server Software

Purpur

### Minecraft Version

1.18.x

### CS-CoreLib Version

- [X] I don't have CS-CoreLib installed

### Slimefun version

This Server uses the following setup of Slimefun:                           
Purpur git-Purpur-1616 (MC: 1.18.2)                          
Slimefun DEV - 1014 (git f431aa6d)                           
Metrics-Module #28                           
Java 17                         
Installed Addons: (50)
Networks vDEV - 34 (git eb71c14d)
ExtraTools vDEV - 34 (git e84a9d59)
FoxyMachines vDEV - 57 (git 2bca6ed7)
SlimefunOreChunks vDEV - 15 (git 2520cb23)
FNAmplifications vDEV - 73 (git 04609677)
SimpleMaterialGenerators vDEV - 4 (git 5543cc8f)
DynaTech vDEV - 165 (git 50b62512)
ElectricSpawners vDEV - 23 (git 6ec96773)
ExtraHeads vDEV - 23 (git 0b59a770)
VillagerUtil vDEV - 1 (git 0a949b19)
SlimyTreeTaps vDEV - 20 (git 963f0383)
PrivateStorage vDEV - 18 (git 5832db21)                            
 FlowerPower vDEV - 14 (git 63a37cc0)
ColoredEnderChests vDEV - 23 (git 4d041832)
Galactifun vDEV - 62 (git 03543cfe)
FluffyMachines vDEV - 116 (git e439acf9)
DyedBackpacks vDEV - 17 (git 8b329e96)
EcoPower vDEV - 5 (git 5c1ecd68)
DankTech2 vDEV - 4 (git 803760fb)
SlimeCustomizer vDEV - 25 (git 4435082d)
SimpleUtils vDEV - 15 (git 4250fd5e)
ElementManipulation vDEV - 21 (git b29aaa3b)
EquivalencyTech v${project.version}
SimpleStorage vDEV - 10 (git ea5e5637)
GlobalWarming vDEV - 11 (git 73ff77d4)                            
CrystamaeHistoria vDEV - 73 (git 528ad08d)
SensibleToolbox vDEV - 46 (git 904daaed)
SfChunkInfo vDEV - 6 (git 56940fbf)
Bump vBuild 18 zh-CN(SlimefunGuguProject) (git 815a92e)<----- This is disabled
ExtraGear vDEV - 13 (git c62047e2)
SFAdvancements vDEV - 18 (git d1feb028)
InfinityExpansion vDEV - 139 (git 1e83e7af)
SFCalc vDEV - 37 (git dfc0fc41)
EMC2 vDEV - 11 (git 89b4400a)                            
MobCapturer vDEV - 17 (git c21b00a5)
SlimeTinker vDEV - 74 (git 5ae433d4)
TranscEndence vDEV - 41 (git 98d7d47e)
SupremeExpansion vDEV - 12 (git 3399568e)
AlchimiaVitae vDEV - 21 (git 27b788bf)
SlimefunWarfare vDEV - 80 (git 364331cf)
HotbarPets vDEV - 38 (git fa6c871d)
SlimefunLuckyBlocks vDEV - 36 (git 60f0c8dc)
ExoticGarden vDEV - 78 (git 7f9a5f63)
HeadLimiter vDEV - 13 (git 8c976b11)
Liquid vDEV - 14 (git 0f5346bf)
LiteXpansion vDEV - 177 (git 2b65056d)
SFMobDrops vDEV - 6 (git d36aba47)
SoulJars vDEV - 23 (git b8358a1f)
PotionExpansion vDEV - 5 (git e2cfcd8a)
SlimyRepair vDEV - 4 (git 790c41cb)

### Plugin version

18

**Comment by ybw0014** [comment]
Well, looks like you set the language option to `en-US`, but in the latest build, the language code changed to `en`.

**Comment by ybw0014** [comment]
I will change the error message, it says the language file `lang/en-US.yml` does not exist in jar, but it is in Chinese right now so you might have no idea what it said.

**Comment by gcars06** [comment]
ok
